spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://csletter-rds-instance.cit8luulctnj.ap-northeast-2.rds.amazonaws.com:3306/csletter_rds?useUnicode=true&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Seoul
    username: admin
    password: Fkdnsemtyfej1!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 12e53c031e79b63b32a7f4d5ee1fbcf2
            redirect-uri: https://chosung-letter.com/oauth/callback/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            client-secret: 6GPRr0LhMpGNyLrArsRxtXeXa53QrIRV
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

cloud:
  aws:
    s3:
      bucket: file-upload-s3-bucket
      folder:

    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: AKIAVYRAAJP22EWXYQFO
      secret-key: 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
      instance-profile: true

jwt:
  secret: 12311564213154321312315631123456789123456789123456789000123

  access:
    expiration: 3600
    header: Authorization

  refresh:
    expiration: 1209600
    header: Authorization-refresh

server:
  error:
    include-exception: true
